In [6]:
import pandas as pd
import plotly.express as px
from pathlib import Path
import country_converter as coco
from UNregionChoroplethGenerator import create_un_region_choropleth

cwd = Path.cwd()
cc = coco.CountryConverter()

# Input paths
results_folder =  cwd.parent / "results"
file_path_scale_up_data = results_folder / "Scale_up_output_MS.csv"

# Output paths
# ECWbyRegionLowerBound_PATH = results_folder / "ECWbyRegionLowerBound.html"
# ECWbyRegionUpperBound_PATH = results_folder / "ECWbyRegionUpperBound.html"
# ECWbyCountryLowerBound_PATH = results_folder / "ECWbyCountryLowerBound.html"
# ECWbyCountryUpperBound_PATH = results_folder / "ECWbyCountryUpperBound.html"

In [9]:
region_list = cc.data['UNregion'].tolist()
scale_df = pd.read_csv(file_path_scale_up_data)
scale_region_df = scale_df[scale_df['Unnamed: 0'].isin(region_list)]

In [42]:
scale_region_df

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,45,46,47,48,49,50,51,52,53,54
216,Australia and New Zealand,2366325,5272682,0,0,(4.6+/-2.4)e+06,(4.6+/-2.4)e+06,(1.3+/-0.4)e+07,(1.5+/-0.4)e+07,(1.6+/-0.4)e+07,...,(6.4+/-0.7)e+07,(6.5+/-0.8)e+07,(6.7+/-0.8)e+07,(6.8+/-0.8)e+07,(6.9+/-0.8)e+07,(7.1+/-0.8)e+07,(7.2+/-0.8)e+07,(7.3+/-0.8)e+07,(7.5+/-0.9)e+07,(7.6+/-0.9)e+07
217,Caribbean,2247673,6734286,0,(2.27+/-0.24)e+05,(2.2+/-0.9)e+06,(2.4+/-0.9)e+06,(3.1+/-0.9)e+06,(3.3+/-0.9)e+06,(3.6+/-0.9)e+06,...,(1.41+/-0.14)e+07,(1.44+/-0.14)e+07,(1.47+/-0.15)e+07,(1.50+/-0.15)e+07,(1.52+/-0.15)e+07,(1.55+/-0.15)e+07,(1.58+/-0.15)e+07,(1.61+/-0.16)e+07,(1.64+/-0.16)e+07,(1.67+/-0.16)e+07
218,Central America,10923315,33415901,0,(7.4+/-0.8)e+04,(1.5+/-0.8)e+07,(1.5+/-0.8)e+07,(2.1+/-0.8)e+07,(2.6+/-0.8)e+07,(3.0+/-0.8)e+07,...,(1.94+/-0.25)e+08,(1.98+/-0.26)e+08,(2.02+/-0.26)e+08,(2.07+/-0.27)e+08,(2.11+/-0.28)e+08,(2.16+/-0.28)e+08,(2.20+/-0.29)e+08,(2.25+/-0.29)e+08,(2.29+/-0.30)e+08,(2.34+/-0.31)e+08
219,Central Asia,4395986,9548737,0,0,(2.3+/-1.2)e+06,(2.3+/-1.2)e+06,(8.0+/-2.4)e+06,(8.3+/-2.4)e+06,(8.7+/-2.4)e+06,...,(2.80+/-0.33)e+07,(2.86+/-0.33)e+07,(2.91+/-0.34)e+07,(2.96+/-0.34)e+07,(3.01+/-0.34)e+07,(3.07+/-0.35)e+07,(3.12+/-0.35)e+07,(3.2+/-0.4)e+07,(3.2+/-0.4)e+07,(3.3+/-0.4)e+07
220,Eastern Africa,25738733,54309550,0,0.0+/-0,0.0+/-0,0.0+/-0,(8.9+/-3.3)e+05,(8.9+/-3.3)e+05,(8.9+/-3.3)e+05,...,(8.9+/-3.3)e+05,(8.9+/-3.3)e+05,(8.9+/-3.3)e+05,(8.9+/-3.3)e+05,(8.9+/-3.3)e+05,(8.9+/-3.3)e+05,(8.9+/-3.3)e+05,(8.9+/-3.3)e+05,(8.9+/-3.3)e+05,(8.9+/-3.3)e+05
221,Eastern Asia,134092816,329015714,0,(5.5+/-0.7)e+07,(6.7+/-1.3)e+08,(7.4+/-1.4)e+08,(1.24+/-0.21)e+09,(1.32+/-0.22)e+09,(1.40+/-0.22)e+09,...,(4.5+/-0.5)e+09,(4.6+/-0.5)e+09,(4.7+/-0.5)e+09,(4.8+/-0.5)e+09,(4.8+/-0.5)e+09,(4.9+/-0.6)e+09,(5.0+/-0.6)e+09,(5.1+/-0.6)e+09,(5.2+/-0.6)e+09,(5.3+/-0.6)e+09
222,Eastern Europe,23045903,46852503,0,0.0+/-0,(2.3+/-1.2)e+07,(2.3+/-1.2)e+07,(5.2+/-1.6)e+07,(5.5+/-1.6)e+07,(6.1+/-1.6)e+07,...,(2.89+/-0.24)e+08,(2.95+/-0.24)e+08,(3.02+/-0.24)e+08,(3.08+/-0.24)e+08,(3.14+/-0.25)e+08,(3.20+/-0.25)e+08,(3.26+/-0.26)e+08,(3.32+/-0.26)e+08,(3.39+/-0.26)e+08,(3.45+/-0.27)e+08
223,Melanesia,619305,1612683,0,0.0+/-0,(2.0+/-1.0)e+04,(2.0+/-1.0)e+04,(1.8+/-0.6)e+05,(1.8+/-0.6)e+05,(1.8+/-0.6)e+05,...,(1.8+/-0.6)e+05,(1.8+/-0.6)e+05,(1.8+/-0.6)e+05,(1.8+/-0.6)e+05,(1.8+/-0.6)e+05,(1.8+/-0.6)e+05,(1.8+/-0.6)e+05,(1.8+/-0.6)e+05,(1.8+/-0.6)e+05,(1.8+/-0.6)e+05
224,Micronesia,22462,58646,0,0.0+/-0,0.0+/-0,0.0+/-0,(4.0+/-1.4)e+04,(4.0+/-1.4)e+04,(4.0+/-1.4)e+04,...,(4.0+/-1.4)e+04,(4.0+/-1.4)e+04,(4.0+/-1.4)e+04,(4.0+/-1.4)e+04,(4.0+/-1.4)e+04,(4.0+/-1.4)e+04,(4.0+/-1.4)e+04,(4.0+/-1.4)e+04,(4.0+/-1.4)e+04,(4.0+/-1.4)e+04
225,Middle Africa,9369410,19642360,0,0.0+/-0,0.0+/-0,0.0+/-0,(5.9+/-2.1)e+04,(5.9+/-2.1)e+04,(5.9+/-2.1)e+04,...,(5.9+/-2.1)e+04,(5.9+/-2.1)e+04,(5.9+/-2.1)e+04,(5.9+/-2.1)e+04,(5.9+/-2.1)e+04,(5.9+/-2.1)e+04,(5.9+/-2.1)e+04,(5.9+/-2.1)e+04,(5.9+/-2.1)e+04,(5.9+/-2.1)e+04
226,Northern Africa,12017413,29083184,0,0.0+/-0,(4.1+/-2.1)e+06,(4.1+/-2.1)e+06,(5.5+/-2.2)e+06,(5.5+/-2.2)e+06,(6.1+/-2.2)e+06,...,(4.4+/-0.4)e+07,(4.5+/-0.4)e+07,(4.6+/-0.4)e+07,(4.7+/-0.4)e+07,(4.8+/-0.5)e+07,(4.9+/-0.5)e+07,(5.0+/-0.5)e+07,(5.1+/-0.5)e+07,(5.2+/-0.5)e+07,(5.3+/-0.5)e+07
227,Northern America,27021498,59574957,0,(2.5+/-0.4)e+07,(3.1+/-0.6)e+08,(3.4+/-0.7)e+08,(4.4+/-0.7)e+08,(4.7+/-0.7)e+08,(5.1+/-0.8)e+08,...,(1.91+/-0.25)e+09,(1.95+/-0.26)e+09,(1.99+/-0.26)e+09,(2.03+/-0.27)e+09,(2.06+/-0.27)e+09,(2.10+/-0.28)e+09,(2.14+/-0.28)e+09,(2.18+/-0.29)e+09,(2.22+/-0.29)e+09,(2.25+/-0.30)e+09
228,Northern Europe,7473021,16386328,0,(2.5+/-0.4)e+07,(3.2+/-0.7)e+08,(3.5+/-0.7)e+08,(3.9+/-0.7)e+08,(4.2+/-0.8)e+08,(4.6+/-0.8)e+08,...,(1.94+/-0.25)e+09,(1.98+/-0.26)e+09,(2.02+/-0.26)e+09,(2.06+/-0.27)e+09,(2.10+/-0.27)e+09,(2.14+/-0.28)e+09,(2.18+/-0.28)e+09,(2.22+/-0.29)e+09,(2.26+/-0.29)e+09,(2.30+/-0.30)e+09
229,Polynesia,33568,81723,0,0.0+/-0,0.0+/-0,0.0+/-0,(4.0+/-1.4)e+04,(4.0+/-1.4)e+04,(4.0+/-1.4)e+04,...,(4.0+/-1.4)e+04,(4.0+/-1.4)e+04,(4.0+/-1.4)e+04,(4.0+/-1.4)e+04,(4.0+/-1.4)e+04,(4.0+/-1.4)e+04,(4.0+/-1.4)e+04,(4.0+/-1.4)e+04,(4.0+/-1.4)e+04,(4.0+/-1.4)e+04
230,South America,29355571,83849131,0,(1.49+/-0.18)e+05,(2.0+/-1.1)e+07,(2.1+/-1.1)e+07,(2.4+/-1.1)e+07,(2.4+/-1.1)e+07,(2.7+/-1.1)e+07,...,(2.20+/-0.21)e+08,(2.26+/-0.21)e+08,(2.31+/-0.22)e+08,(2.36+/-0.22)e+08,(2.41+/-0.22)e+08,(2.46+/-0.23)e+08,(2.52+/-0.23)e+08,(2.57+/-0.24)e+08,(2.62+/-0.24)e+08,(2.67+/-0.24)e+08
231,South-eastern Asia,54372904,138751581,0,(7.8+/-1.1)e+04,(2.9+/-1.5)e+07,(3.0+/-1.5)e+07,(7.4+/-2.1)e+07,(8.1+/-2.1)e+07,(8.9+/-2.1)e+07,...,(3.98+/-0.30)e+08,(4.06+/-0.31)e+08,(4.15+/-0.31)e+08,(4.23+/-0.32)e+08,(4.32+/-0.32)e+08,(4.40+/-0.32)e+08,(4.48+/-0.33)e+08,(4.57+/-0.33)e+08,(4.65+/-0.34)e+08,(4.73+/-0.34)e+08
232,Southern Africa,3414558,10510151,0,0.0+/-0,(1.9+/-1.0)e+06,(1.9+/-1.0)e+06,(1.8+/-0.6)e+07,(1.8+/-0.6)e+07,(1.9+/-0.6)e+07,...,(3.9+/-0.7)e+07,(4.0+/-0.7)e+07,(4.0+/-0.7)e+07,(4.1+/-0.7)e+07,(4.2+/-0.7)e+07,(4.2+/-0.7)e+07,(4.3+/-0.7)e+07,(4.3+/-0.7)e+07,(4.4+/-0.7)e+07,(4.4+/-0.7)e+07
233,Southern Asia,152774494,291437630,0,(7.6+/-1.1)e+05,(2.7+/-1.3)e+07,(3.3+/-1.3)e+07,(1.26+/-0.35)e+08,(1.32+/-0.35)e+08,(1.39+/-0.35)e+08,...,(4.1+/-0.5)e+08,(4.2+/-0.5)e+08,(4.3+/-0.5)e+08,(4.4+/-0.5)e+08,(4.4+/-0.5)e+08,(4.5+/-0.5)e+08,(4.6+/-0.5)e+08,(4.7+/-0.5)e+08,(4.7+/-0.5)e+08,(4.8+/-0.5)e+08
234,Southern Europe,10239028,24154381,0,(1.92+/-0.20)e+05,(2.9+/-1.3)e+07,(3.4+/-1.3)e+07,(4.6+/-1.3)e+07,(5.1+/-1.3)e+07,(5.8+/-1.3)e+07,...,(3.31+/-0.33)e+08,(3.39+/-0.34)e+08,(3.46+/-0.35)e+08,(3.54+/-0.35)e+08,(3.6+/-0.4)e+08,(3.7+/-0.4)e+08,(3.8+/-0.4)e+08,(3.8+/-0.4)e+08,(3.9+/-0.4)e+08,(4.0+/-0.4)e+08
235,Western Africa,17250115,47388443,0,(4.3+/-0.6)e+05,(3.4+/-1.3)e+06,(3.8+/-1.3)e+06,(4.5+/-1.3)e+06,(5.0+/-1.4)e+06,(5.4+/-1.4)e+06,...,(2.14+/-0.30)e+07,(2.19+/-0.31)e+07,(2.23+/-0.32)e+07,(2.27+/-0.32)e+07,(2.32+/-0.33)e+07,(2.36+/-0.33)e+07,(2.40+/-0.34)e+07,(2.45+/-0.35)e+07,(2.49+/-0.35)e+07,(2.5+/-0.4)e+07
236,Western Asia,15940382,39023753,0,(1.98+/-0.15)e+05,(2.3+/-1.2)e+07,(2.4+/-1.2)e+07,(3.4+/-1.2)e+07,(3.7+/-1.2)e+07,(4.1+/-1.2)e+07,...,(1.78+/-0.17)e+08,(1.81+/-0.17)e+08,(1.85+/-0.17)e+08,(1.89+/-0.17)e+08,(1.93+/-0.18)e+08,(1.96+/-0.18)e+08,(2.00+/-0.18)e+08,(2.04+/-0.18)e+08,(2.07+/-0.19)e+08,(2.11+/-0.19)e+08
237,Western Europe,14939189,31147282,0,(1.26+/-0.13)e+07,(1.58+/-0.34)e+08,(1.74+/-0.35)e+08,(2.0+/-0.4)e+08,(2.2+/-0.4)e+08,(2.4+/-0.4)e+08,...,(1.01+/-0.09)e+09,(1.03+/-0.10)e+09,(1.05+/-0.10)e+09,(1.07+/-0.10)e+09,(1.09+/-0.10)e+09,(1.11+/-0.10)e+09,(1.13+/-0.11)e+09,(1.15+/-0.11)e+09,(1.17+/-0.11)e+09,(1.19+/-0.11)e+09

In [41]:
TimeToCover_region_df = pd.DataFrame()
TimeToCover_region_df['Region'] = scale_region_df['Unnamed: 0']
for row in scale_region_df.iterrows():
    region = row[1][0]
    print(row[1][])

5272682
6734286
33415901
9548737
54309550
329015714
46852503
1612683
58646
19642360
29083184
59574957
16386328
81723
83849131
138751581
10510151
291437630
24154381
47388443
39023753
31147282

C:\Users\seabr\AppData\Local\Temp\ipykernel_24316\2925320011.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  region = row[1][0]
C:\Users\seabr\AppData\Local\Temp\ipykernel_24316\2925320011.py:5: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(row[1][2])

                        Region
216  Australia and New Zealand
217                  Caribbean
218            Central America
219               Central Asia
220             Eastern Africa
221               Eastern Asia
222             Eastern Europe
223                  Melanesia
224                 Micronesia
225              Middle Africa
226            Northern Africa
227           Northern America
228            Northern Europe
229                  Polynesia
230              South America
231         South-eastern Asia
232            Southern Africa
233              Southern Asia
234            Southern Europe
235             Western Africa
236               Western Asia
237             Western Europe